# http://module-build.sourceforge.net/META-spec.html
# XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Ustream-API-User
version:      0.01
version_from: lib/WebService/Ustream/API/User.pm
installdirs:  site
requires:
    URI::Fetch:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30

